# Generated by Django 3.1.11 on 2021-05-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommdityInfos',
            new_name='CommodityInfos',
        ),
    ]
